---
# vars file for device-discovery.yml tasks

# If any of the words in this list are found in the the devices 'host' or 'links.ids' or 'model'
# sections of the localhost Ansible Facts, the device will be suggested as an installation target
trigger_words:
  - "usb"