---
# vars file for image-get.yml tasks
shorthand_versions:
  - 'full'
  - 'desktop'
  - 'lite'

raspbian_os:
  full: "Raspbian Desktop With Recommended Software"
  desktop: "Raspbian Desktop"
  lite: "Raspbian Lite"

raspbian_urls:
  full: "https://downloads.raspberrypi.org/raspios_full_armhf_latest"
  desktop: "https://downloads.raspberrypi.org/raspios_armhf_latest"
  lite: "https://downloads.raspberrypi.org/raspios_lite_armhf_latest"

raspbian_type_rule:
  full: '(?=.*full)(?=.*\.img$)' # Must contain 'full'
  desktop: '^(?=.*raspios)((?!full|lite).)*(\.img)$' # Does not contain 'full' or 'lite', but contains 'raspios'
  lite: '(?=.*lite)(?=.*\.img$)' # Must contain 'lite'