- block:
  - debug:
      msg: "Which OS version you wish to install? Your options are [1] Raspbian Desktop with recommended software, [2] Raspbian Desktop, [3] Raspbian lite (headless)."
  - pause:
      prompt: 'Please enter [1,2, or 3] from above'
    register: selection
    delegate_to: localhost

  - set_fact:
      os_version: "{{ selection.user_input }}"

- fail:
    msg: "Error: please type 1, 2, or 3. Aborting..."
  when: os_version not in num_select

- debug:
    msg: "You've selected to install {{ raspbian_os[os_version | int - 1] }}"

- block:
  - pause:
      prompt: "Is this correct (y/n)?"
    register: selection
    delegate_to: localhost

  - set_fact:
      decision: "{{ selection.user_input }}"

- fail:
    msg: "Installation aborted."
  when: decision | lower == "n" or decision | lower == "no"

- name: Checking if Raspbian file is cached
  # This block includes an optimization to check the headers of the url for the filename to ftd_file_download
  # If this filename is already found in the files folder of the role, we don't need to download it.
  block:
  - uri:
      url: "{{ raspbian_urls[os_version | int - 1] }}"
      method: HEAD
    register: uri_test

  - set_fact:
      os_filename: "{{ uri_test.url | regex_search('([0-9a-zA-Z\\._\\-]+).zip') | replace('.zip', '.img') }}"

  - find:
      path: "{{ role_path }}/files/"
      patterns: '{{ raspbian_type_rule[os_version | int - 1] }}'
      use_regex: yes
    register: find_result
  
  # As long as the user does not mess with the state of the files folder and Raspian naming conventions continue, we can assume the 0'th index is the file name we want
  - set_fact:
      file_on_disk: "{{ 'null' if (find_result.matched == 0) else find_result.files[0].path | regex_search('([0-9a-zA-Z\\._\\-]+).img') }}"
  - block:
  # Old OS file or file not found, delete and update with latest version
    - block:
      - debug:
          msg: "Found file {{ file_on_disk }}, which is not the latest version of Raspian. Deleting..."
      
      - name: Removing old image file to save space
        file:
          path: "{{ role_path }}/files/{{ file_on_disk }}"
          state: absent
      when: file_on_disk != 'null'
    
    - name: Downloading latest version of Raspbian...
      unarchive:
        src: "{{ raspbian_urls[os_version | int - 1] }}"
        dest: "{{ role_path }}/files/"
        remote_src: yes
        mode: "600"
      # Only do this when the local machine state is not correct
    - set_fact:
        file_on_disk: "{{ os_filename }}"
    when:  file_on_disk != os_filename

  - debug:
      msg: "Found file {{ file_on_disk }}, which will be installed."
