- fail:
    msg: "os_version variable must be one of: 'lite', 'desktop', 'full'"
  when: os_version not in shorthand_versions

- debug:
    msg: "Raspbian Version: {{ raspbian_os[os_version] }}"
    verbosity: 1

- name: Checking if Raspbian file is cached
  # This block includes an optimization to check the headers of the url for the filename to ftd_file_download
  # If this filename is already found in the files folder of the role, we don't need to download it.
  block:
  - uri:
      url: "{{ raspbian_urls[os_version] }}"
      method: HEAD
    register: uri_test

  - set_fact:
      os_filename: "{{ uri_test.url | regex_search('([0-9a-zA-Z\\._\\-]+).zip') | replace('.zip', '.img') }}"

  - find:
      path: "{{ role_path }}/files/"
      patterns: '{{ raspbian_type_rule[os_version] }}'
      use_regex: yes
    register: find_result
  
  # As long as the user does not mess with the state of the files folder and Raspian naming conventions continue, we can assume the 0'th index is the file name we want
  - set_fact:
      file_on_disk: "{{ 'null' if (find_result.matched == 0) else find_result.files[0].path | regex_search('([0-9a-zA-Z\\._\\-]+).img') }}"
  - block:
  # Old OS file or file not found, delete and update with latest version
    - block:
      - debug:
          msg: "Found file {{ file_on_disk }}, which is not the latest version of Raspian. Deleting..."
          verbosity: 1

      - name: Removing old image file to save space
        file:
          path: "{{ role_path }}/files/{{ file_on_disk }}"
          state: absent
      when: file_on_disk != 'null'
    
    - name: Downloading latest version of Raspbian...
      unarchive:
        src: "{{ raspbian_urls[os_version] }}"
        dest: "{{ role_path }}/files/"
        remote_src: yes
        mode: "600"
      # Only do this when the local machine state is not correct
    - set_fact:
        file_on_disk: "{{ os_filename }}"
    when:  file_on_disk != os_filename

  - debug:
      msg: "Found file {{ file_on_disk }}, which will be installed."
      verbosity: 1
